spec file fixes - missing directories
This will fix spec file installations:

First:
Error in configuration file '/etc/icinga/icinga.cfg' - Line 465

Line 465:
check_result_path=/var/log/icinga/spool/checkresults
-----

Second:
Error: Could not create external command file '/var/log/icinga/rw/icinga.cmd' as named pipe: (2) -> No such file or directory.

Thanks to 'Ziben' - IssueID #106